### ISSUE TITLE
yaml module not in requirements

### ISSUE THREAD

**Issue by NicoleP23** [wrightedu/CSE-Discord-Bot#105]
**Describe the bug**
yaml is not in REQUIREMENTS.txt

**To Reproduce**
`pip install -R REQUIREMENTS.txt`

**Expected behavior**
yaml included and there isn't an error that it isn't

**Screenshots**
![image](https://user-images.githubusercontent.com/70728308/154136152-adbb3271-e287-457a-b61d-658e699514ef.png)

**Comment by CodingPenguin1** [comment]
Require `PyYAML >= 6.0`
