### ISSUE TITLE
CSV file not found error

### ISSUE THREAD

**Issue by ReginPotter** [wrightedu/CSE-Discord-Bot#113]
## Describe the bug
If you run the *buildserver* command and do not have the __**role_lists**__ folder an error will occur and not let you build the server
The error is in the *destroyserver* command

## To Reproduce
1. Start up the bot
2. Delete role_lists folder or double check you do not have this folder
3. Execute the buildserver command

## Expected behavior
The bot will throw a FileNotFoundException when trying to find the role_lists directory

## Screenshot
![image](https://user-images.githubusercontent.com/77698810/166504190-ca1891d3-9cb9-44db-90b7-2bea5446bd4e.png)
![image](https://user-images.githubusercontent.com/77698810/166504318-e0cfd01c-0d36-4072-ae84-4f7a1a085bd1.png)

## Discord Link
[Error](https://discord.com/channels/808423775048564807/817441972134084649/971091194228637716)

## Additional context
In order to fix this problem we can make the error more pretty to the user
We could also do a test that prompts the user to skip the removing of the roles
We could also try to create a CSV from scratch

**Comment by mbozada** [comment]
Closed by #118
