### ISSUE TITLE
Classlist Generation Script

### ISSUE THREAD

**Issue by mbozada** [wrightedu/CSE-Discord-Bot#124]
**Who are you?**
CSE Dev Team Member

**What feature do you want?**
A rigorous python script that generates class list .csv's from wright state wing's class look up page.

**Why do you want this feature?**
It would make creating classlists much easier.

**Additional context**
Check out PR #92 as well as [classlist_csv_from_pdf.py](https://github.com/wrightedu/CSE-Discord-Bot/blob/development/Classlists/classlist_csv_from_pdf.py). If the script works well, or if we make a new script that works, we should add the function to [utils.py](https://github.com/wrightedu/CSE-Discord-Bot/blob/development/utils.py)

**Comment by NicoleP23** [comment]
Note: This isn't a priority, but definitely want to look into this at some point
