### ISSUE TITLE
Active Message Reading

### ISSUE THREAD

**Issue by ReginPotter** [wrightedu/CSE-Discord-Bot#126]
**Who are you?**
CSE Dev Team

**What feature do you want?**
Make the bot read all messages and follow a/multiple channel(s)

Stretch goal: Reply "That looks interesting" to every message that contains a '?'
Next Stretch goal: Make a command that can turn the listening on or off for a specific channel

Super Stretch goal: Figure out ratelimits and whether or not this will break the bot
What would happen if it was listening everywhere, what would happen to the ratelimit

**Why do you want this feature?**
This would help the FAQ command to be an active command that the bot automatically deals with rather than us manually doing it

**Additional context**
Any questions about this talk to Matt Kijowski, he was the one that started this conversation and this idea

**Comment by mkijowski** [comment]
super stretch armstrong goal, rate limits
