### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by mbozada** [wrightedu/CSE-Discord-Bot#142]
**Describe the bug**
Upon shutdown a crazy error message is sent out. Nothing bad happens, but I think the move to discord.py 2.0 has broken something. Or something we added after the fact.

**To Reproduce**
1. Run your bot
2. Run `-shutdown` and `confirm` when prompted
3. Check out the terminal

**Expected behavior**
The bot shutdown should be a clean exit.

**Screenshots**
![image](https://user-images.githubusercontent.com/52613673/181346444-e87c99ef-308e-4033-8ff6-5d3e1d6f6947.png)

**Comment by ReginPotter** [comment]
This still happens, and should be looked at
