### ISSUE TITLE
createrolebutton issue with emojis

### ISSUE THREAD

**Issue by NicoleP23** [wrightedu/CSE-Discord-Bot#152]
**Describe the bug**
When trying to have an emoji in the role name or button name, 

**To Reproduce**
1. Use `/createrolebutton`
2. Add ":emoji:" with the role or button name
3. Role and button should look like screenshot below (we used the ":acm:" emoji)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/70728308/183701061-77f2bcd3-4f93-4fa6-98e6-547fc0fbbc22.png)

**Comment by ReginPotter** [comment]
The `/createrolebutton` command now has emoji capability however the only way to use this command is to put something into the emoji parameter. I am currently working on a way to make this parameter optional, however, for now type any random string into the emoji field if you do not want an emoji for it.

**Comment by ReginPotter** [comment]
Currently this issue is on hold. In the code there are ways to cause an argument to be optional, however, this is not critical right now.

**Comment by ReginPotter** [comment]
@NicoleP23  has the answer for this, see if she can work on this!
