### ISSUE TITLE
Event creation for faculty

### ISSUE THREAD

**Issue by ReginPotter** [wrightedu/CSE-Discord-Bot#173]
**Who are you?**
CSE Dev Team, Regin Potter

**What feature do you want?**
I want to have the feature for Faculty to create Events. Currently one of the CSE Support team needs to create the event for them.
This causes a lot of back and forth of questioning in order to have all the information for the event creation.

**Why do you want this feature?**
The current system is not the best, it would work much better for any faculty to create an event.

**Comment by L30N1DAS** [comment]
Faculty now have the "Manage Events" permission. This entails creating, editing, and canceling events.
