### ISSUE TITLE
`/checkin`

### ISSUE THREAD

**Issue by Kokuko3** [wrightedu/CSE-Discord-Bot#174]
**Who are you?**

Mason McDaniel CSE Dev

**What feature do you want?**

Create a new command to give a time when we check in to the office with a "commit message" to display our current tasks and objectives. After calling checkin will prompt with three buttons and create a weekly "calendar". 
- Checkout: End work session
- Help: Adds a help message at the current time to the calendar and asks for help.
- Pomodoro (Pomeranian): Prompts a message to set out 15 minutes to do a single task.

**Why do you want this feature?**

For productivity amongst the CSE dev team. 

**Additional context**

After the 15 minute cycle must send a picture of a Pomeranian.

**Comment by L30N1DAS** [comment]
Notes for Mason on starting checkin
* /checkin
* debate with the team where it should go
  * make Anmol/Nazby figure out if buttons should have methods or functions elsewhere
* get user name and output it `"Matt Kijowski" is checking in`
* get timestamp and output it with above
* provide input to /checkin (-m for a check in message)
* output that message '"Matt Kijowski" is starting at "Date/Time" and working on "-m"'
* Buttons!!!!!

move GMs to 1:15pm on Mondays (Retrospective on fridays, same time)

**Comment by Kokuko3** [comment]
# Notes on Pomodoro Button

- Send out message
- Give buttons for start and stop timer
- Once timer is done, prompt for new message (And send photo of Pomeranian)

**Comment by Kokuko3** [comment]
### Checkin Rework

**Comment by Kokuko3** [comment]
### Checkin Rework

- DM menus for Pomodoro
- Help Command Functionality TBD
- Data for time sheet
      1. UUID
      2. Username
      3. Time Start
      4. Time Done
      5. Task (String)
      6. ? (YN? Count?)
- Command or Button Checkout?
- When you click any button, 1/25 of a Pomeranian GIF

**Comment by NicoleP23** [comment]
Edge case of pomodoro done/not done with tasks, but checkout was clicked, what should happen?
Should it be allowed? Or should they have to say done/not done for pomodoro first before checking out?

If not done clicked, message prompted as to why (so future you remembers)?

-Potentially optional button for any time to make a comment/message in pomodoro, whether it's for the "done" button or "not done" button 
(add to Data for time sheet: a string for this)

**Comment by Kokuko3** [comment]
Recommend adding a new embedded view that allows us to visually see the current status of workers at a glance.

**Comment by JakeHamblin** [comment]
Was completed in #395 PR
