### ISSUE TITLE
`corgme` extracts images in a weird order

### ISSUE THREAD

**Issue by L30N1DAS** [wrightedu/CSE-Discord-Bot#193]
**Describe the bug**
`images = ['dogs/corgis/' + path.name for path in Path('dogs').rglob('*.*')]` makes the list in a strange yet unknown order (i.e., when corgme is run on a particular number, the correct numbered image is not retrieved). `sorted(Path('dogs').rglob('*.*'))` will sort the list alphabetically, but `image_10.jpg` will precede `image_2.jpg`, still outputting the incorrect image.

**To Reproduce**
1. Put `print(f"{number}")` and `print(f"{images[number]}")` after `image = images[number]`
2. Turn on bot and run -corgme
3. Observe that the printed numbers do not match

**Expected behavior**
The output image's number should match the entered number

**Screenshots**
![image](https://user-images.githubusercontent.com/77419369/206768640-566dcd20-cb8b-42ba-acad-83333c2f11ce.png)

**Comment by ReginPotter** [comment]
I honestly dont think this matters. To the student it is giving them the correct image so it is fine to me.
