### ISSUE TITLE
Load, Reload, and Unload

### ISSUE THREAD

**Issue by L30N1DAS** [wrightedu/CSE-Discord-Bot#210]
**Describe the bug**
`/load`, `/unload`, and `/reload` give unexpected output and do not function correctly

**To Reproduce**
1. Go to "CSE Testing Server"
2. Turn on your bot
3. Run `/reload AdminCommands`
    Output: `Cog AdminCommands is unloaded`
4. Run `/load AdminCommands`
    Output: `Cog AdminCommands is already loaded`
5. Run `unload AdminCommands`
    Output: `Cog AdminCommands has been unloaded`

**Expected behavior**
`/load` should load if not already loaded
`/reload` should reload if already loaded
`/unload` should unload if already loaded

**Screenshots**
<img width="486" alt="Screen Shot 2023-01-25 at 5 05 30 PM" src="https://user-images.githubusercontent.com/77419369/214702175-529092c0-f957-47d3-808e-a7e36a4dbf16.png">
<img width="486" alt="Screen Shot 2023-01-25 at 5 06 20 PM" src="https://user-images.githubusercontent.com/77419369/214702333-369e5206-ae74-4e4e-b2d0-fb930b6754cb.png">

**Comment by ReginPotter** [comment]
I tried recreating this issue and it did not reporoduce. Please help recreate this issue.

**Comment by ReginPotter** [comment]
@L30N1DAS

**Comment by ReginPotter** [comment]
Cannot replicate so issue will be closed
