### ISSUE TITLE
Dropdown menu for Cog Management

### ISSUE THREAD

**Issue by ReginPotter** [wrightedu/CSE-Discord-Bot#211]
**Who are you?**
Regin Potter, CSE Dev Team member

**What feature do you want?**
I want every command (besides sync) in the Cog Management file to have a drop-down menu instead of us typing it in.

**Why do you want this feature?**
Currently we need to type in the name of the file. If we mess up the name we must re-issue the command.
This feature would be more Quality-of-Life, however I think it would be nice to implement.

**Additional context**
Some information I found was [here](https://gist.github.com/lykn/a2b68cb790d6dad8ecff75b2aa450f23).

**Comment by ReginPotter** [comment]
Two potential solutions that work:
Option 1:
![image](https://user-images.githubusercontent.com/77698810/226394762-a931740d-93d8-435e-9fad-4cc99575d456.png)
![image](https://user-images.githubusercontent.com/77698810/226395244-1fd51bb8-f92c-4845-8a52-21e8b43f4037.png)

Option 2:
![image](https://user-images.githubusercontent.com/77698810/226394892-f2fa3701-c807-48c4-9c2d-f66abb80b139.png)
![image](https://user-images.githubusercontent.com/77698810/226395404-27e90551-2aa0-441a-aee6-ec3aa67aafb9.png)

**Comment by ReginPotter** [comment]
We are going with Option 1 because of @L30N1DAS

**Comment by L30N1DAS** [comment]
> We are going with Option 1 because of @L30N1DAS

Meeting with team complete and this was agreed upon by the entire team
