### ISSUE TITLE
Checkin error

### ISSUE THREAD

**Issue by ReginPotter** [wrightedu/CSE-Discord-Bot#216]
**Describe the bug**
When running `/checkin` it will error at times.

**To Reproduce**
1. Run `/checkin hello`
2. See error in terminal

**Expected behavior**
This should produce an error saying "unknown interaction".

**Screenshots**
![image](https://user-images.githubusercontent.com/77698810/226464852-c9e1f183-5532-4527-8980-652d08268ab2.png)

**Additional context**
I am unsure if this error is reproducible however it is still important to check out at least once

**Comment by kaelabook** [comment]
`/checkin` is being re-done :D
