### ISSUE TITLE
Server Stats Command

### ISSUE THREAD

**Issue by CodingPenguin1** [wrightedu/CSE-Discord-Bot#25]
Should show total channels (out of Discord's max limitation), user count, users by role, class count, activity, and whatever else we can think of

**Comment by CodingPenguin1** [comment]
Messages over time by major would also be cool

**Comment by L30N1DAS** [comment]
Thinking of adding most messaged-in channel over last 24 hrs, user who sent most messages in last 24 hrs, and most @ed user in last 24 hrs.

**Comment by mbozada** [comment]
Closed by #112
