### ISSUE TITLE
Moss mediator code 

### ISSUE THREAD

**Issue by kaelabook** [wrightedu/CSE-Discord-Bot#254]
**Who are you?**
CSE Dev Team Member

**What feature do you want?**
I want to be able run the code (either Dr. Cheatham's or Ali Aljaffer's) that is necessary to fully run Moss.

**Why do you want this feature?**
This is necessary to completely run Moss. Maybe one day we can make a bash script that is easier.

**Comment by kaelabook** [comment]
We tested Ali's code and were able to get it to run on this linux system. His code is good and works well. Should be able to get it to work on the discord bot.

**Comment by mkijowski** [comment]
New PEP8 string
"""Run MOSS command
* perform a lookup from /moss-register and return the MOSS ID (issue #258)
* download (see `/build-courses`) the student submission .zip to `/tmp/<mossid>`
* run ali's code in `/tmp/<moss_id>`
* call Mason's perl script with `-i <moss_id>`


Prereqs:
    User must be in an approved group (TA, Faculty, Dev-team, cse-support)
    This command must be run in approved channels: (#TA-MOSS)
    User must have run /moss-register previously

Args:
    upload_file (file): similar to course management upload file

Outputs:
    MOSS URL
