### ISSUE TITLE
Moss Command Exit

### ISSUE THREAD

**Issue by Kokuko3** [wrightedu/CSE-Discord-Bot#264]
**Describe the bug**
Moss Command does not exit unless a zip file is specified. We should allow for an option for the user to exit the program prematurely if necessary.

**To Reproduce**
Run `/test` and then attempt to run another command

**Comment by BPennie03** [comment]
https://discordpy.readthedocs.io/en/stable/api.html?highlight=wait_for#discord.Client.wait_for
