### ISSUE TITLE
`/feedme` does not properly remove restaurants from the list

### ISSUE THREAD

**Issue by BPennie03** [wrightedu/CSE-Discord-Bot#281]
**Describe the bug**
Removing restaurants apparently does not work properly? Idk, Matt said so

**To Reproduce**
1. Run `/feedme` command
2. Try to remove a restaurant in the list
3. Notice it is not properly removed

**Expected behavior**
The restaurant should be removed from the list

**Comment by kaelabook** [comment]
Kinda done but also not really
