### ISSUE TITLE
If a channel is created after user has a role they are unable to see it

### ISSUE THREAD

**Issue by Kokuko3** [wrightedu/CSE-Discord-Bot#300]
**Describe the bug**
The IEEE officers created a new channel in there discord section and the user's were unable to see the new channel unless they removed and reassigned the role to themselves

**To Reproduce**
1. Assign role
2. Create channel hidden for only that specific role
3. Check to see if channel is visible

**Expected behavior**
Channel should be visible

**Comment by JakeHamblin** [comment]
The issue appears to be with a Discord caching issue client side. This has been a common bug with Discord itself and requires a full restart (CTRL + R) of Discord to fix sometimes. They may also have some channels hidden, causing it to not immediately show that channel. Closing this issue as 'Won't Fix'.
