### ISSUE TITLE
Blast command

### ISSUE THREAD

**Issue by CodingPenguin1** [wrightedu/CSE-Discord-Bot#34]
@mkijowski  forgets that the news channel exists and sends news in every individual channel. We'd like to automate this. Send arg string to every text channel (watch out for @everyone though)

**Comment by mbozada** [comment]
@CodingPenguin1 So for this command, you want to able to:

-blast "Hello everyone!"

And "Hello everyone!" will be posted in every text channel on the server?

Who should have access to the command, and do you have any additional features in mind?

**Comment by CodingPenguin1** [comment]
Sorry, yeah haven't updated all the old issues to the new format.

Only admins should have access to this command.

Should send to every channel as you described, though having the ability to specify only a few or exclude a few would be nice. Ex:

`-blast --include #channel-1 #channel-2` to just send to those 2 channels

or

`-blast --exclude #channel-1 #channel-2` to send to all, excluding, those 2 channels
