### ISSUE TITLE
MOSS does not run as expected on `development` or any branch

### ISSUE THREAD

**Issue by kaelabook** [wrightedu/CSE-Discord-Bot#378]
**Describe the bug**
When I try to test moss in the testing server, I can run moss and it asks for a .zip file, but when I give it the file it gives prints this exception out in the terminal:

`Command 'moss' raised an exception: IndexError: list index out of range`

**To Reproduce**
1. Go onto dev branch
2. Start bot
3. Run `/moss` in ta-moss
4. Give a .zip file (if you need one, you can ask me)
5. Watch the terminal

**Expected behavior**
After I give the .zip file, it should take 30+ seconds or so to print out the url

**Comment by JakeHamblin** [comment]
This issue exists as a result of the use of `python3` in the code while the standard development SIF uses `python`. This has been documented in a recent PR and I had @mkijowski verify that a symlink exists between `python3` and `python`.
