### ISSUE TITLE
Unable to report `checkin report-monthly` from the BOT DM view

### ISSUE THREAD

**Issue by bibekrj** [wrightedu/CSE-Discord-Bot#413]
**Describe the bug**
`checkin report-monthly works from within discord testing server. However, the user should be able to interact with this functionality from the BOT direct message/conversation view. 

Currently, when the user tries to enter the role for the report, the bot view is unable to generate&/present the list of roles to user. 

Typing in the user role 'verbatim' also results in **role not found** error. 

**Expected behavior**
The user should be able to generate report from the bot interaction view/conversation and NOT in the server. 
_Potentially because the report could be considered sensitive information_

**Comment by JakeHamblin** [comment]
This is not the intended functionality. While we can implement the Guild tracking in the backend, the overall idea is to have Guild-specific runs for future development. Marking this as closed.
