### ISSUE TITLE
Check/validate roleid in clearrole command in AdminCommands.py

### ISSUE THREAD

**Issue by BJblair20** [wrightedu/CSE-Discord-Bot#56]

**Comment by CodingPenguin1** [comment]
@BJblair20 can you please provide a more detailed description of the problem?

**Comment by tux2603** [comment]
I don't think that this will be necessary, the `discord.utils.get` method being used will already return `None` if no matching code is found, which should already be handled by the following code. The only issue that could pop up is it printing out something like `No members have the role @None`, but it won't crash or raise any errors
