### ISSUE TITLE
Connossieur Role and Command

### ISSUE THREAD

**Issue by mbozada** [wrightedu/CSE-Discord-Bot#88]
As a member of the CS Dev Team, I want a role that gains access to a /where2eat (subject to change) command so that the Dev Team can decide where to eat lunch easily.

Features:
- [ ] Add Restaurant
- [ ] Remove Restaurant
- [ ] Randomly Select Restaurant
- [ ] Restaurants should go on a week long cooldown once selected
- [ ] Random Pool limited by type of food(?)

**Comment by ReginPotter** [comment]
Add the ability to add a restaurant to either Vegan or Random.

Add a message that tells the user that the restaurant was added.
