### ISSUE TITLE
Fix rate limiting on all looping commands

### ISSUE THREAD

**Issue by CodingPenguin1** [wrightedu/CSE-Discord-Bot#90]
**Describe the bug**
According to the [Discord API Docs](https://discord.com/developers/docs/topics/rate-limits), bots can only send requests 50 times per second. The bot does not currently have any protection against rate limiting itself and therefore can reach a hard rate limit. 

**To Reproduce**
1. Run -buildserver a few too many times

**Expected behavior**
Commands that have looping requests to the Discord API should not break because they were used a few times.

**Screenshots**
```
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-hnsh",{"micros":158619,"calls":["discord-sessions-green-prd-2-134",{"micros":156260,"calls":["start_session",{"micros":153325,"calls":["api-prd-main-kct2",{"micros":142365,"calls":["get_user",{"micros":22006},"add_authorized_ip",{"micros":10516},"get_guilds",{"micros":18466},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":2435,"calls":[]}]}]}] (Session ID: 058d3d7f915fd304baee7dd5780ca201).






[2021-08-20 07:47:39] ###################################
[2021-08-20 07:47:39] # BOT STARTING FROM FULL SHUTDOWN #
[2021-08-20 07:47:40] ###################################
[2021-08-20 07:47:45] Loaded cog: StudentCommands
[2021-08-20 07:47:45] Loaded cog: Listeners
[2021-08-20 07:47:46] Loaded cog: AdminCommands
empty role menu dict
[2021-08-20 07:47:47] Loaded cog: ServerManagement
[2021-08-20 07:47:47] Loaded cog: CogManagement
[2021-08-20 07:47:47] Bot is online
[2021-08-20 07:47:51] #########################
[2021-08-20 07:47:51] # BOT STARTUP COMPLETED #
[2021-08-20 07:47:51] #########################

[2021-08-20 07:47:51] Started in 14.5 seconds
creating role
WARNING:discord.http:We are being rate limited. Retrying in 132221.50 seconds. Handled under the bucket "None:808423775048564807:/guilds/{guild_id}/roles"
```

**Additional context**
Use `await asyncio.sleep()` to sleep

**Comment by mbozada** [comment]
It's time to find a proper fix.

**Comment by ReginPotter** [comment]
As far as we know discord.py gives a soft ratelimit so we dont hit discord's rate limit. All we can do to stop this is to avoid using async commands in loops without a clear terminating condition.

**Comment by kaelabook** [comment]
Here are some sources to Regin's claim.

https://discordpy.readthedocs.io/en/stable/api.html?highlight=rate%20limit#discord.RateLimited

For this one, it's in the list of features:
https://discordpy.readthedocs.io/en/stable/
